"""initial generation tables

Revision ID: a13f086e26e4
Revises: 
Create Date: 2024-06-04 21:39:36.042342

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a13f086e26e4'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('generation',
    sa.Column('uid', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('created', 'in_progress', 'finished', 'failed', name='generationstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('input_img_path', sa.String(), nullable=False),
    sa.Column('input_prompt', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_table('generation_result',
    sa.Column('uid', sa.UUID(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('finished_at', sa.DateTime(), nullable=False),
    sa.Column('img_path', sa.String(), nullable=True),
    sa.Column('error', sa.String(), nullable=True),
    sa.Column('generation_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['generation_id'], ['generation.uid'], ),
    sa.PrimaryKeyConstraint('uid')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('generation_result')
    op.drop_table('generation')
    sa.Enum(name="generationstatus").drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
