"""Add description and negative prompt columns

Revision ID: c141faeb5892
Revises: a13f086e26e4
Create Date: 2024-06-12 16:16:12.564933

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c141faeb5892'
down_revision: Union[str, None] = 'a13f086e26e4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('generation', sa.Column('description', sa.String(), nullable=True))
    op.add_column('generation', sa.Column('negative_prompt', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('generation', 'negative_prompt')
    op.drop_column('generation', 'description')
    # ### end Alembic commands ###
