---
- hosts: all
  become: yes
  vars:
    yap_api_tag: 9504111802
    yap_cr_path: cr.yandex/crpqi7c93korf1gmhgn1
    yap_api_image: "{{ yap_cr_path }}/yap/back"
    yap_cr_login: oauth
    yap_cr_pass: "secret"
  tasks:
    - name: Login to cr.yandex
      community.docker.docker_login:
        registry_url: cr.yandex
        username: "{{ yap_cr_login }}"
        password: "{{ yap_cr_pass }}"
        reauthorize: true
    
    - name: Pull yap image
      community.docker.docker_image_pull:
        name: "{{ yap_api_image }}"
        tag: "{{ yap_api_tag }}"

    - name: Run migration
      community.docker.docker_container:
        name: yap_api_migrate_01
        image: "{{ yap_api_image }}:{{ yap_api_tag }}"
        state: started
        restart: true
        network_mode: host
        command: yap-db upgrade head
        env: # see yap_back/yap/settings.py
          PG_URL: "postgresql://yap:crackme@127.0.0.1:5432/yap"
    
    - name: Ensure yap_api container is present
      community.docker.docker_container:
        name: yap_api_01 
        image: "{{ yap_api_image }}:{{ yap_api_tag }}"
        state: started
        restart: true
        network_mode: host
        env: # see yap_back/yap/settings.py
          PG_URL: "postgresql://yap:crackme@127.0.0.1:5432/yap"
          APP_ENV: "prod"
          APP_HOST: "0.0.0.0"
          APP_PORT: "8080"
          MINIO_ENDPOINT: "127.0.0.1:9091"
          YC_OAUTH_TOKEN: "secret"
          # note, created manually
          MINIO_ACCESS_KEY: dvB68mlI2enNB8hsHeu9
          MINIO_SECRET_KEY: AonnuBp3CKUsgvA9MhrOnuOzGqdUOVUEKojAaT9y
          MINIO_CDN_PATH: https://yawt.ru/cdn

    - name: Ensure yap_worker container is present
      community.docker.docker_container:
        name: yap_worker_01
        image: "{{ yap_api_image }}:{{ yap_api_tag }}"
        state: started
        restart: true
        network_mode: host
        command: yap-worker worker
        env: # see yap_back/yap/settings.py
          PG_URL: "postgresql://yap:crackme@127.0.0.1:5432/yap"
          APP_ENV: "prod"
          APP_HOST: "0.0.0.0"
          APP_PORT: "8080"
          MINIO_ENDPOINT: "127.0.0.1:9091"
          YC_OAUTH_TOKEN: "secret"
          # note, created manually
          MINIO_ACCESS_KEY: dvB68mlI2enNB8hsHeu9
          MINIO_SECRET_KEY: AonnuBp3CKUsgvA9MhrOnuOzGqdUOVUEKojAaT9y
          MINIO_CDN_PATH: https://yawt.ru/cdn
