---
- hosts: all
  become: yes
  vars:
    yap_api_tag: 9468886180
    yap_cr_path: cr.yandex/crpqi7c93korf1gmhgn1
    yap_api_image: "{{ yap_cr_path }}/yap/back"
    yap_cr_login: oauth
    yap_cr_pass: "secret"
  tasks:
    - name: Login to cr.yandex
      community.docker.docker_login:
        registry_url: cr.yandex
        username: "{{ yap_cr_login }}"
        password: "{{ yap_cr_pass }}"
        reauthorize: true
    - name: Pull yap_api image
      community.docker.docker_image_pull:
        name: "{{ yap_api_image }}"
        tag: "{{ yap_api_tag }}"
    - name: Ensure yap_api container is present
      community.docker.docker_container:
        name: yap_api_01 
        image: "{{ yap_api_image }}:{{ yap_api_tag }}"
        state: started
        restart: true
        network_mode: host
        default_host_ip: 0.0.0.0
        ports:
          - "8080:8080"
        exposed_ports:
          - "8080:8080"
        env: # see yap_back/yap/settings.py
          PG_URL: "postgresql://user:crackme@localhost:5432/yap"
          APP_ENV: "prod"
          APP_PORT: "8080"
          MINIO_ENDPOINT: "127.0.0.1:9091"
          # note, created manually
          MINIO_ACCESS_KEY: dvB68mlI2enNB8hsHeu9
          MINIO_SECRET_KEY: AonnuBp3CKUsgvA9MhrOnuOzGqdUOVUEKojAaT9y
