name: Dockerize yap-back

on: workflow_dispatch

jobs:

  build:
  
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: cr.yandex
          username: ${{ secrets.YA_CLOUD_CR_USERNAME }}
          password: ${{ secrets.YA_CLOUD_CR_PASSWORD }}
      -
        name: Build and push yap-back
        uses: docker/build-push-action@v5
        with:
          context: ./yap-back/
          platforms: linux/amd64
          push: true
          file: ./yap-back/build/Dockerfile
          tags: cr.yandex/crp5ssrvkgu8uop1839g/yap/back:${{ github.run_id }}
